import keys from '../../../assets/soundfonts/keys.sfpack?url';
import mallets from '../../../assets/soundfonts/mallets.sfpack?url';
import guitars from '../../../assets/soundfonts/guitars.sfpack?url';
import strings from '../../../assets/soundfonts/strings.sfpack?url';
import winds from '../../../assets/soundfonts/winds.sfpack?url';
import brass from '../../../assets/soundfonts/brass.sfpack?url';
import electronic from '../../../assets/soundfonts/electronic.sfpack?url';
import percussion from '../../../assets/soundfonts/percussion.sfpack?url';
import nylon from '../../../assets/soundfonts/nylon.sfpack?url';
import steel from '../../../assets/soundfonts/steel.sfpack?url';
import piano from '../../../assets/soundfonts/piano.sfpack?url';
import bass from '../../../assets/soundfonts/bass.sfpack?url';
import drumkit from '../../../assets/soundfonts/drumkit.sfpack?url';
import electricClean from '../../../assets/soundfonts/electricClean.sfpack?url';
import electricDrive from '../../../assets/soundfonts/electricDrive.sfpack?url';
import bandoneon from '../../../assets/soundfonts/bandoneon.sfpack?url';
import upright from '../../../assets/soundfonts/upright.sfpack?url';
import type { BankId } from './presets';
export const bankURLs: Record<BankId, string> = { keys, mallets, guitars, strings, winds, brass, electronic, percussion, nylon, steel, piano, bass, drumkit, electricClean, electricDrive, bandoneon, upright };
