import { useEffect, useMemo, useState } from 'react';
import { Sheet, NoteCard } from './Sheet';
import { getStylesForGenre } from '../engine/style/registry';
import type { SongStyle } from '../data/styles/schema';
import { plateFor } from './worlds';
import { fullSongs, type FullSongTemplate } from '../data/songs/catalog';
import { RECORDING_ARRANGEMENTS } from '../data/songs/recordingArrangements';

/**
 * Song style — the flavour of the current genre (Pugliese-school, Vals, Electrotango…).
 *
 * Displays a clean column of style names with a concise 1-2 line summary that highlights
 * what makes each style stick out, plus a ° note button for full details.
 */
export function StyleSheetModal({
  open,
  onClose,
  currentGenreId,
  currentStyleId,
  onPickStyle,
  onPickSong,
  currentCatalogId,
}: {
  open: boolean;
  onClose: () => void;
  currentGenreId: string;
  currentStyleId?: string;
  onPickStyle: (styleId: string) => void;
  onPickSong: (songId: string) => void;
  currentCatalogId?: string;
}) {
  const [mode, setMode] = useState<'full-song' | 'sample'>('full-song');
  const songs = fullSongs.filter(entry => entry.genreId === currentGenreId);
  const [note, setNote] = useState<{ title: string; body: string; tags: string[] } | null>(null);

  useEffect(() => {
    if (!open) setNote(null);
  }, [open]);

  const plate = plateFor(currentGenreId);

  // The genre's usual style leads; the rest keep the catalogue's own order.
  const styles = useMemo(() => {
    const all = getStylesForGenre(currentGenreId);
    return [...all.filter(s => s.canonical), ...all.filter(s => !s.canonical)];
  }, [currentGenreId]);

  const openSongNote = (entry: FullSongTemplate) => {
    const authored = RECORDING_ARRANGEMENTS[entry.referenceKey];
    setNote({ title: entry.track, body: [
      `${entry.artist} — ${entry.track}`,
      entry.arrangementBasis === 'recording-informed'
        ? 'Recording-informed score adaptation. Section lengths and chord cells are approximate; melody is generated by the existing style.'
        : 'Style-derived full arrangement. Uses the existing style’s form, harmony, instruments and tone; the recording’s exact structure and chords have not been transcribed.',
      entry.description,
      entry.selectedFromRepertoire ? 'Representative track selected from the referenced repertoire or dance scene.' : null,
      authored?.source ? `Source: ${authored.source}` : null,
    ].filter(Boolean).join('\n\n'), tags: [entry.styleName, entry.arrangementBasis === 'recording-informed' ? 'Score adaptation' : 'Style-derived'] });
  };

  const openNote = (s: SongStyle) => {
    const tempo = s.rhythm?.tempoRange ? `${s.rhythm.tempoRange[0]}–${s.rhythm.tempoRange[1]} bpm` : null;
    const reference = s.reference
      ? `${s.reference.credit}${s.reference.recording ? ` — ${s.reference.recording}` : ''}`
      : null;
    const instruments = [...new Set((s.sound?.instrumentPalette ?? []).map(item => item.value))];
    const mix = s.calibration?.mix?.character;
    const mixSummary = mix ? [
      (mix.dryness ?? 0.5) >= 0.68 ? 'dry room' : (mix.dryness ?? 0.5) <= 0.4 ? 'roomy ambience' : 'moderate room',
      (mix.bassForward ?? 0.5) >= 0.68 ? 'bass-forward' : (mix.bassForward ?? 0.5) <= 0.4 ? 'lighter low end' : 'balanced low end',
      (mix.width ?? 0.5) >= 0.68 ? 'wide stereo' : (mix.width ?? 0.5) <= 0.4 ? 'compact stereo' : 'natural stereo width',
      (mix.brightness ?? 0.5) >= 0.68 ? 'bright transients' : (mix.brightness ?? 0.5) <= 0.4 ? 'warm/dark tone' : 'balanced tone',
    ].join(' · ') : null;
    setNote({
      title: s.name,
      body: [
        reference ? `Reference: ${reference}` : null,
        s.calibrationQualities?.length ? `Sonic cues: ${s.calibrationQualities.slice(0, 6).join('; ')}` : s.summary,
        instruments.length ? `Ensemble palette: ${instruments.join(', ')}` : null,
        mixSummary ? `Mix: ${mixSummary}` : null,
      ].filter((line): line is string => !!line).join('\n\n'),
      tags: [s.rhythm?.meter, tempo, s.region].filter((t): t is string => !!t),
    });
  };

  return (
    <>
      <Sheet open={open} onClose={onClose} title="Songs & samples" kicker={plate.short}>
        <div className="flex gap-2 mb-3" role="group" aria-label="Catalog type">
          <button className="btn-pill" aria-pressed={mode === 'full-song'} onClick={() => setMode('full-song')}>Full songs</button>
          <button className="btn-pill" aria-pressed={mode === 'sample'} onClick={() => setMode('sample')}>Samples</button>
        </div>
        <div className="micro mb-3">{mode === 'full-song' ? 'Reference arrangements using the existing styles. Choose a song to start over.' : 'Original style studies. Choose a sample to start over.'}</div>
        {mode === 'full-song' && <div className="flex flex-col">
          {songs.map(entry => <div key={entry.id} className="flex items-stretch border-b border-current/10">
            <button type="button" className="text-left py-3 flex-1 min-w-0" aria-pressed={entry.id === currentCatalogId}
              onClick={() => { onPickSong(entry.id); onClose(); }}>
              <span className="block text-sm font-medium">{entry.track}</span>
              <span className="micro block mt-1">{entry.artist} · {entry.styleName}</span>
              <span className="micro block opacity-60 mt-1">{entry.arrangementBasis === 'recording-informed' ? 'Score adaptation' : 'Style-derived arrangement'}</span>
            </button>
            <button type="button" className="slab px-3 opacity-50 hover:opacity-100" style={{ fontSize: 24 }} aria-label={`About ${entry.track}`} onClick={() => openSongNote(entry)}>°</button>
          </div>)}
        </div>}

        {styles.length === 0 && (
          <div className="micro py-4">No styles for this genre yet.</div>
        )}

        <div className="flex flex-col" hidden={mode !== 'sample'}>
          {styles.map((s, i) => {
            const active = !currentCatalogId?.endsWith('_song') && (s.id === currentStyleId || (!currentStyleId && !!s.canonical));
            return (
              <div
                key={s.id}
                className="flex items-stretch"
                style={{ borderTop: i === 0 ? 'none' : '1px solid color-mix(in srgb, var(--ink) 12%, transparent)' }}
              >
                <button
                  type="button"
                  onClick={() => { onPickStyle(s.id); onClose(); }}
                  aria-pressed={active}
                  className="text-left py-2.5 flex items-center gap-2.5 sm:gap-3 flex-1 min-w-0"
                >
                  <span
                    style={{
                      width: 4,
                      alignSelf: 'stretch',
                      background: 'var(--signal)',
                      opacity: active ? 1 : 0.45,
                      flexShrink: 0,
                    }}
                  />
                  <span style={{ minWidth: 0, flex: 1 }}>
                    <span className="flex items-baseline gap-1.5">
                      <span
                        className="truncate"
                        style={{ fontSize: 14, fontWeight: active ? 600 : 400, lineHeight: 1.2 }}
                      >
                        {s.name}
                      </span>
                      {s.canonical && <span className="micro shrink-0">· usual</span>}
                    </span>
                    <span className="micro block opacity-75 leading-snug line-clamp-2 mt-0.5">
                      {s.summary}
                    </span>
                  </span>
                </button>
                <button
                  type="button"
                  onClick={() => openNote(s)}
                  aria-label={`About ${s.name}`}
                  className="slab shrink-0 px-3 opacity-50 hover:opacity-100 transition-opacity"
                  style={{ fontSize: 24 }}
                >
                  °
                </button>
              </div>
            );
          })}
        </div>
      </Sheet>

      <NoteCard
        open={!!note}
        onClose={() => setNote(null)}
        title={note?.title ?? ''}
        body={note?.body ?? ''}
        tags={note?.tags}
      />
    </>
  );
}
