// CALIBRATE: derive per-instrument makeupGain from rendered audio so every instrument lands on the same
// reference level at unit track gain. Writes src/data/sound/calibratedMakeup.ts (read first by makeupGainFor).
// Run: npm run calibrate:makeup            (add --check to verify the committed file is current + unclamped)
// Method: render several notes x velocities at volume=1, take the median per-note peak, makeup = REF / peak.
import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import OfflineRenderer from '@elemaudio/offline-renderer';
import { INSTRUMENTS_BY_ID } from '../../src/data/instruments';
import { getLuthierModelForInstrument } from '../../src/engine/playback/luthier.ts';
import { defaultTrackParams, midiToFreq, modelForInstrument, renderTrack } from '../../src/engine/playback/elementaryEngine.ts';
import { resolveRenderGesture } from '../../src/engine/playback/renderGesture.ts';
import { codeForGesture } from '../../src/engine/band/gestures.ts';

// Reference: peak (dBFS) of one note at velocity 0.8, unit track gain, before role/genre offsets. Role dB then
// places lead/bass/comp relative to this. -12 leaves room for the role offsets to stay under -3 dBFS.
const REF_PEAK_DB = -8;
const MAKEUP_MIN = 0.05, MAKEUP_MAX = 20; // a value outside this means the DSP voice needs fixing, not more gain
const VELOCITIES = [0.5, 0.8, 1.0];
const OUT = 'src/data/sound/calibratedMakeup.ts';
const sampleRate = 44100, blockSize = 256, measureSeconds = 1.5;
const renderer = new OfflineRenderer();
const outputs = [new Float32Array(blockSize), new Float32Array(blockSize)];
const median = (a: number[]) => [...a].sort((x, y) => x - y)[Math.floor(a.length / 2)];

function notesFor(def: any): number[] {
  const kit = def.kitComponents?.map((k: any) => k.midi).filter((m: any) => typeof m === 'number');
  if (kit?.length) return kit.slice(0, 3);
  const lo = def.tuningAndMechanics?.keyRange?.lowMidi ?? 48, hi = def.tuningAndMechanics?.keyRange?.highMidi ?? lo + 24;
  return [lo + 2, Math.round((lo + hi) / 2), hi - 5];
}

async function measure(def: any): Promise<number> {
  const id = def.id;
  const luthier = def.luthierPhysics ?? getLuthierModelForInstrument(id);
  const params = defaultTrackParams(id, luthier, modelForInstrument(id));
  params.volume = 1; // unit gain: no makeup, role or genre
  const gestureName = def.techniques.articulations[0] ?? 'tone';
  const gesture = resolveRenderGesture(id, codeForGesture(gestureName));
  const peaks: number[] = [];
  for (const midi of notesFor(def)) for (const velocity of VELOCITIES) {
    const trackId = `cal-${id}-${midi}-${velocity}`;
    const voice = { id: `${trackId}-v`, note: midi, velocity, gate: 1, frequencyHz: midiToFreq(midi),
      action: gesture.action, excitationType: gesture.excitationType, articulation: gesture.articulationNorm };
    renderer.reset();
    const sig = renderTrack(trackId, [voice], params);
    await renderer.render(sig.left, sig.right);
    let peak = 0;
    for (let b = 0; b < Math.ceil(sampleRate * measureSeconds / blockSize); b++) {
      renderer.process([], outputs);
      for (let i = 0; i < blockSize; i++) peak = Math.max(peak, Math.abs(outputs[0][i]), Math.abs(outputs[1][i]));
    }
    if (peak > 1e-8) peaks.push(peak / velocity); // normalise to unit velocity, then rescale to 0.8 below
  }
  return peaks.length ? median(peaks) * 0.8 : 0;
}

async function main() {
  await renderer.initialize({ sampleRate, numInputChannels: 0, numOutputChannels: 2, blockSize });
  const map: Record<string, number> = {}; const peaks: Record<string, number> = {}; const bad: string[] = [];
  for (const def of Object.values(INSTRUMENTS_BY_ID) as any[]) {
    try {
      const peak = await measure(def);
      if (!(peak > 0)) { bad.push(`${def.id}: silent at every note/velocity`); continue; }
      const makeup = 10 ** (REF_PEAK_DB / 20) / peak;
      if (makeup < MAKEUP_MIN || makeup > MAKEUP_MAX) bad.push(`${def.id}: makeup ${makeup.toFixed(3)} outside [${MAKEUP_MIN}, ${MAKEUP_MAX}] (raw peak ${(20 * Math.log10(peak)).toFixed(1)} dBFS) - fix the DSP voice`);
      map[def.id] = +makeup.toFixed(3); peaks[def.id] = peak;
    } catch (e) { bad.push(`${def.id}: ${e instanceof Error ? e.message : e}`); }
  }
  const body = `// GENERATED by scripts/calibrate/makeup.ts (npm run calibrate:makeup). Do not hand-edit.\n// makeup = 10^(${REF_PEAK_DB}/20) / median peak at unit gain, velocity 0.8.\nexport const CALIBRATED_MAKEUP: Record<string, number> = ${JSON.stringify(map, null, 2)};\n`;
  if (process.argv.includes('--check')) {
    const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
    const drift = Object.entries(map).filter(([k, v]) => { const m = cur.match(new RegExp(`"${k}": ([0-9.]+)`)); return !m || Math.abs(20 * Math.log10(+m[1] / v)) > 1; });
    if (drift.length) bad.push(`${drift.length} instrument(s) drifted >1 dB from calibratedMakeup.ts: ${drift.slice(0, 8).map(d => d[0]).join(', ')}`);
  } else { writeFileSync(OUT, body); mkdirSync('audit', { recursive: true }); writeFileSync('audit/instrument-peaks.json', JSON.stringify(peaks, null, 1)); }
  console.log(JSON.stringify({ instruments: Object.keys(map).length, problems: bad.length }, null, 2));
  bad.forEach(b => console.error('  - ' + b));
  if (bad.length) process.exitCode = 1;
}
main();
