import type { PerformanceMode } from '../../data/styles/contracts';
import type { TechniqueMechanics } from '../../data/performance/techniqueMechanics';
import type { SynthPatch } from '../../data/instruments/schema/instrument-def';

export interface VoiceState {
  mechanics?: TechniqueMechanics;
  bodyAttack?: 'golpe' | 'golpe-caja';
  noteDurationSeconds?: number;
  soundParams?: TrackParams;
  controllerKeys?: Array<'articulation' | 'brightness' | 'contact' | 'mute' | 'bowPressure' | 'bowVelocity' | 'bodyTap' | 'pluckPosition' | 'pressure' | 'resonance'>;
  note: number;
  velocity: number;
  gate: number;
  id: string;
  action?: string;
  excitationType?: 'plectrum' | 'nail' | 'fingerpad' | 'hard-pick' | 'hammer' | 'stick' | 'mallet' | 'breath' | 'bow' | string;
  contactPoint?: number;
  mass?: number;
  frequencyHz?: number;
  bellowsDirectionCode?: 1 | 2;
  bandoneonButtonId?: string;
  bandoneonButtonIndex?: number;
  bandoneonSideCode?: 1 | 2;
  retriggerId?: number;
  attack?: number;
  decay?: number;
  sustain?: number;
  release?: number;
  articulation?: number;
  baseFrequencyHz?: number;
  triggerSeq?: number;
  noteInstanceId?: string;
  harmonicRichnessDelta?: number;
  decayTimeFactorScale?: number;
}

export interface TrackParams {
  brightness: number;
  decay: number;
  drive: number;
  body: number;
  tension: number;
  styleFlavor: number;
  articulation: number;
  contact: number;
  mute: number;
  bowPressure: number;
  bowVelocity: number;
  bodyTap: number;
  pluckPosition: number;
  pressure: number;
  resonance: number;
  model: string;
  pan: number;
  dialect?: string;
  genreId?: string;
  performanceMode?: PerformanceMode;
  bendGlideMs?: number;
  instrumentId?: string;
  courses?: number;
  bodyConstruction?: 'wood-box' | 'gourd' | 'skin-faced' | 'board' | 'solid-electric' | 'metal-shell' | 'brass-tube';
  excitationType?: 'plectrum' | 'nail' | 'fingerpad' | 'hard-pick' | 'hammer' | 'stick' | 'mallet' | 'breath' | 'bow';
  sympatheticStrings?: boolean;
  variantId?: string;
  registration?: string;
  rotary?: boolean;
  synthPatchId?: string;
  synthPatch?: SynthPatch;
  roleGain?: number;
}
